backgammon/urls.py
from django.urls import path

from .views import *

app_name = 'backgammon'


urlpatterns = [
            path('', view=homepage, name='homepage'),
            path('celebrate/', celebration, name='celebration')
        ]

blog/urls.py
from django.conf.urls import url, include

from .views import *


urlpatterns = [
    url(r'^$', view=blog_homepage,name='blog_homepage'),
    url(r'^(?P<slug>[-\w]+)/$', view=blog_category,name='blog_category'),
    url(r'^create/$', view=create_post,name='blog_create'),
    url(r'^edit/(?P<slug>[-\w]+)/$', view=edit_post,name='blog_edit'),
    url(r'^detail/(?P<slug>[-\w]+)/$', view=blog_details, name='blog_detail'),




    ]

portofolio/urls.py
from django.conf.urls import url, include
from django.urls import path
from django.contrib import admin
from homepage.views import *
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from django.views.generic.base import RedirectView
from newsletter.views import subscribe
from blog.views import *
from short_url.views import *
from funny_projects.views import *
from sample_templates.views import TemplateListView
from homepage.sitemaps import StaticViewSitemap, ProjectSitemap


sitemaps = {
    'static': StaticViewSitemap,
    'projects': ProjectSitemap
}

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^my-cookie-law/$', view=my_cookie_law, name='my_cookie_law'),
 

    #  english
    url(r'^$', HomePageEng.as_view(), name='homepage_eng'),
    url(r'^about/$', AboutEng.as_view(), name='about_eng'),
    url(r'^projects/$', WorksEng.as_view(), name='gallery_eng'),
    url(r'^blog/$', BlogPageEng.as_view(), name='blog_eng'),
    url(r'^blog/(?P<slug>[-\w]+)/$', PostPageEng.as_view(), name='blog_page_eng'),
    url(r'^project/(?P<slug>[-\w]+)/$', ProjectPageEng.as_view(), name='project_page_eng'),
    url(r'^subscribe/$', view=subscribe, name='subscribe'),

    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^sitemap.xml',sitemap, {'sitemaps': sitemaps}),
    #  url(r'^robots\.txt$', include('robots.urls')),

    #  funny projects
    url(r'^gym/$', view=GymPage.as_view(), name='gym_page'),
    url(r'^gym/(?P<dk>\d+)/$', view=gym_person_page, name='gym_page_id'),
    path('backgammon/', include('backgammon.urls', namespace='backgammon')),


    #  test_urls
    url(r'^create_blog/$', view=blog_create, name='create_blog'),
    url(r'^basic-upload/$', BasicUploadView.as_view(), name='basic_upload'),
    url(r'^like/(?P<slug>[-\w]+)/$', PostLike.as_view(), name='like'),
    url(r'^cache-clear/$', view=cache_clear, name='cache_clear'),
    #url(r'^api/like/(?P<slug>[-\w]+)/$', PostLikeApi.as_view(), name='api_like'),

    #  short_code module
    url(r'^shorting-url/$', ShortHomepage.as_view(), name='shorting_url'),
    url(r'^s/(?P<slug>[-\w]+)/$', view=redirect_view, name='redirect_result'),

    #  sample templates
    url(r'^sample-templates/$', TemplateListView.as_view(), name='sample-templates')

    #url(r'^.*$', RedirectView.as_view(url='/', permanent=False), name='index'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

homepage/models.py
from django.db import models

# Create your models here.


def about_upload(instance, filename):
    pass


def welcome_upload(instance, filename):
    return 'homepage/%s/%s' % (instance.title, filename)


def banner_upload(instance, filename):
    return 'banner/%s/%s' % (instance.title, filename)


def tech_upload(instance, filename):
    return 'tech/%s/%s' % (instance.title, filename)


class WelcomePage(models.Model):
    active = models.BooleanField(default=True)
    title = models.CharField(max_length=100)
    seo_keywords = models.CharField(max_length=160, null=True, blank=True)
    seo_description = models.CharField(max_length=160, null=True, blank=True)
    title_eng = models.CharField(unique=True, max_length=100)
    seo_keywords_eng = models.CharField(max_length=160, null=True, blank=True)
    seo_description_eng = models.CharField(max_length=160, null=True, blank=True)

    class Meta:
        verbose_name_plural = '1. Διαχείριση Αρχικής Σελίδας'

    def __str__(self):
        return self.title


class MainBanner(models.Model):
    title = models.CharField(max_length=100)
    alt = models.CharField(max_length=100)
    title_eng = models.CharField(max_length=100)
    alt_eng = models.CharField(max_length=100)
    image = models.ImageField(upload_to=banner_upload)
    page_related = models.ForeignKey(WelcomePage, null=True, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = 'Main Banner - Using static files atm for that'

"""
<h3 class="subtitle wow fadeInUp" data-wow-delay=".3s" data-wow-duration="500ms">Why We are Different</h3>
                    <p  class="wow fadeInUp" data-wow-delay=".5s" data-wow-duration="500ms">
                            Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequun. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                        </p>
                        <p  class="wow fadeInUp" data-wow-delay=".7s" data-wow-duration="500ms">
                            Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae.
                        </p>
"""


class AboutMe(models.Model):
    title = models.CharField(max_length=50, default='default')
    text = models.TextField(blank=True)
    title_eng = models.CharField(max_length=50, default='default')
    text_eng = models.TextField(blank=True)
    page_related = models.ForeignKey(WelcomePage, null=True, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = '2. About Me Info'

    def __str__(self):
        return self.title


class AboutMeBar(models.Model):
    title = models.CharField(max_length=100)
    percent = models.IntegerField(default=50)
    page_related = models.ForeignKey(WelcomePage, null=True, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = 'About Programming Skill Bar - No use atm'

    def __str__(self):
        return self.title


class Services(models.Model):
    icon = models.CharField(max_length=100, null=True, help_text='Here you use bootstrap icons, you can find them here. http://bootstrapmaster.com/live/one/icons_set2.html')
    title = models.CharField(max_length=100)
    text = models.TextField(max_length=400)
    title_eng = models.CharField(max_length=100)
    text_eng = models.TextField(max_length=400)
    order = models.IntegerField(default=1)
    active = models.BooleanField(default=True)
    page_related = models.ForeignKey(WelcomePage, null=True, on_delete=models.CASCADE)

    class Meta:
        ordering = ['order']
        verbose_name_plural = '3. Services'

    def __str__(self):
        return self.title


class Contact(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    subject = models.CharField(max_length=100)
    message = models.TextField()
    day_added = models.DateField(auto_now_add=True)
    is_readed = models.BooleanField(default=False)

    def __str__(self):
        return '%s - %s'%(self.day_added, self.name)


class AboutPage(models.Model):
    active = models.BooleanField(default=True)
    title = models.CharField(max_length=50)
    keywords = models.CharField(max_length=160, blank=True, null=True)
    description = models.CharField(max_length=160, blank=True, null=True)
    title_eng = models.CharField(max_length=50)
    keywords_eng = models.CharField(max_length=160, blank=True, null=True)
    description_eng = models.CharField(max_length=160, blank=True, null=True)

    class Meta:
        verbose_name_plural = '4. Διαχείριση About Σελίδας'

    def __str__(self):
        return self.title


class AboutMessages(models.Model):
    title = models.CharField(max_length=50)
    text = models.TextField()
    title_eng = models.CharField(max_length=50)
    text_eng = models.TextField()
    delay = models.CharField(default='.3s', max_length=5)
    page_related = models.ForeignKey(AboutPage, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = '5. Διαχείριση About Μυνημάτων'

    def __str__(self):
        return self.title


class AboutTecho(models.Model):
    active = models.BooleanField(default=True)
    image = models.ImageField(upload_to=tech_upload)
    title = models.CharField(max_length=50)
    text = models.TextField()
    title_eng = models.CharField(max_length=50)
    text_eng = models.TextField()
    page_related = models.ForeignKey(AboutPage, on_delete=models.CASCADE)
    delay = models.CharField(max_length=5, default='.3s')

    class Meta:
        verbose_name_plural = '6. Διαχείριση About Τεχνολογίες'

    def __str__(self):
        return self.title


class AboutClients(models.Model):
    active = models.BooleanField(default=True)
    image = models.ImageField()
    title = models.CharField(max_length=50)
    page_related = models.ForeignKey(AboutPage, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = '7. Διαχείριση About Πελάτες'

    def __str__(self):
        return self.title

projects/models.py
from django.db import models
from django.shortcuts import reverse
from .validators import validate_image
from tinymce.models import HTMLField
# Create your models here.


class ProjectCategory(models.Model):
    title = models.CharField(max_length=70)
    title_eng = models.CharField(max_length=70)

    def __str__(self):
        return self.title


class ImageProductManager(models.Manager):
    def active(self):
        return super(ImageProductManager, self).filter(active=True)

    def post_related_and_active(self, post):
        return super(ImageProductManager, self).filter(active= True, project_related=post)

    def post_related(self, post):
        return super(ImageProductManager, self).filter(project_related = post)


class ProjectsManager(models.Manager):
    def active(self):
        return super(ProjectsManager, self).filter(active=True)

    def demo_sites(self):
        return super(ProjectsManager, self).filter(active= True, demo=True)

    def first_page(self):
        return self.active().filter(show_first_page=True)


class Projects(models.Model):
    active = models.BooleanField(default=True)
    show_first_page = models.BooleanField(default=False)
    active_eng = models.BooleanField(default=True)
    title = models.CharField(max_length=255,)
    short_description = models.CharField(max_length=255, help_text='The text appears on homepage')
    description = HTMLField()
    seo_description = models.CharField(max_length=255, blank=True, null=True)
    seo_keywords = models.CharField(max_length=255, blank=True, null=True)
    slug = models.SlugField(blank=True, null=True, allow_unicode=True)
    title_eng = models.CharField(max_length=255, default='Insert Text')
    short_description_eng = models.CharField(max_length=255, help_text='The text appears on homepage', default='Insert Text')
    description_eng = HTMLField(default='Insert Text')
    seo_description_eng = models.CharField(max_length=255, blank=True, null=True, default='Insert Text')
    seo_keywords_eng = models.CharField(max_length=255, blank=True, null=True, default='Insert Text')
    image = models.ImageField()
    category = models.ForeignKey(ProjectCategory, on_delete=models.CASCADE)
    day_added = models.DateField(auto_now_add=True)
    href = models.CharField(max_length=255, blank=True, null=True)
    github = models.URLField(blank=True, null=True)
    demo = models.BooleanField(default=False)
    my_query = ProjectsManager()
    objects = models.Manager()

    class Meta:
        verbose_name_plural = 'Project'

    def __str__(self):
        return self.title

    def additional_images_active(self):
        return ImageProject.my_query.post_related_and_active(post=self)

    def additional_images(self):
        return ImageProject.my_query.post_related(post=self)

    def tag_demo(self):
        return 'Demo Site' if self.demo else 'Site'

    def get_absolute_url(self):
        return reverse('project_page_eng', kwargs={'slug': self.slug})


class ImageProject(models.Model):
    title = models.CharField(max_length=60)
    alt = models.CharField(max_length=60, null=True, blank=True)
    image = models.ImageField(validators=[validate_image, ])
    text = models.TextField(blank=True, null=True, verbose_name='Optional description.')
    project_related = models.ForeignKey(Projects, on_delete=models.CASCADE)
    active = models.BooleanField(default=True)
    objects = models.Manager()
    my_query = ImageProductManager()

    def __str__(self):
        return self.title

blog/forms.py
from django import forms
from .models import *
from PIL import Image

MAX_FILE_SIZE = 2*1024*1024


class PostCreate(forms.ModelForm):
    title = forms.CharField(label="Τίτλος 'Αθρου", widget=forms.TextInput(attrs={'onkeyup':"myTitle()",}))
    lead_content = forms.CharField(label='Πρώτα Σχόλια', widget=forms.Textarea(attrs={'onkeyup':"myLeadCon()",}))
    content = forms.CharField(label='Βασικό Κείμενο', widget=forms.Textarea(attrs={'onkeyup':"myCon()",}))
    #content = forms.CharField(label='Βασικό Κείμενο', widget=FroalaEditor(attrs={'onkeyup':"myCon()",}))
    #user = forms.ChoiceField(widget=forms.HiddenInput())
    #publish = forms.DateTimeField(widget=forms.DateTimeField())

    class Meta:
        model = Post
        fields = '__all__'
        exclude = ['publish','user']


class PostTagForm(forms.ModelForm):

    class Meta:
        model = PostTags
        fields = '__all__'

class PostCategoryForm(forms.ModelForm):

    class Meta:
        model = PostCategory
        fields = '__all__'


class PhotoForm(forms.ModelForm):
    x = forms.FloatField(widget=forms.HiddenInput())
    y = forms.FloatField(widget=forms.HiddenInput())
    width = forms.FloatField(widget=forms.HiddenInput())
    height = forms.FloatField(widget=forms.HiddenInput())
    title = forms.CharField(widget=forms.TextInput(attrs={'onkeyup':"myTitle()",}))
    content = forms.CharField(widget=forms.Textarea(attrs={'onkeyup':"myContent()",}))

    class Meta:
        model = Post
        fields = '__all__'

    def save(self):
        photo = super(PhotoForm, self).save()
        x = self.cleaned_data.get('x')
        y = self.cleaned_data.get('y')
        w = self.cleaned_data.get('width')
        h = self.cleaned_data.get('height')

        image = Image.open(photo.file)
        cropped_image = image.crop((x, y, w+x, h+y))
        resized_image = cropped_image.resize((200, 200), Image.ANTIALIAS)
        resized_image.save(photo.file.name)
        return photo


class GalleryForm(forms.ModelForm):
    class Meta:
        model = Gallery
        fields = ['file']

    def clean_file(self):
        file = self.cleaned_data.get('file')
        if file:
            if file._size > MAX_FILE_SIZE:
                raise forms.ValidationError('This file is bigger than 2 mb')
            return file
        else:
            raise forms.ValidationError('Something wrong with this file')

newsletter/forms.py
from django import forms
from .models import *
import mailchimp
from django.conf import settings


class JoinForm(forms.ModelForm):
    accept_ = forms.BooleanField(required=True)
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control',
                                                            'placeholder': 'Γράψτε το email σας',
                                                            })
                             )
    
    class Meta:
        model = Join
        fields = ['email', 'accept_']

    def clean(self):
        email = self.cleaned_data.get('email')
        qs = Join.objects.filter(email=email)
        if qs.exists():
            raise forms.ValidationError('Έχετε χρησιμοποιήσει ήδη αυτό το Email')
        API_KEY = settings.MAILCHIMP_API_KEY
        LIST_ID = settings.MAILCHIMP_SUBSCRIBE_LIST_ID
        api = mailchimp.Mailchimp(API_KEY)
        try:
            api.lists.subscribe(LIST_ID, {'email': email})
        except:
            pass


class JoinFormEng(forms.ModelForm):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control',
                                                            'placeholder': 'Fill with your email',
                                                            })
                             )

    class Meta:
        model = Join
        fields = ['email']

    def clean(self):
        email = self.cleaned_data.get('email')
        qs = Join.objects.filter(email=email)
        if qs.exists():
            raise forms.ValidationError('This email is allready subsribed')
        API_KEY = settings.MAILCHIMP_API_KEY
        LIST_ID = settings.MAILCHIMP_SUBSCRIBE_LIST_ID
        api = mailchimp.Mailchimp(API_KEY)
        try:
            api.lists.subscribe(LIST_ID, {'email': email})
        except:
            pass

projects/views.py
from django.shortcuts import render

# Create your views here.

homepage/templates/tim/index.html
<!DOCTYPE html> {% load static %}
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" name="viewport" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta property="og:url"                content="{{ request.path }}" />
    <meta property="og:image"              content="{% static 'assets/img/logo.png' %}" />
    {% block seo %}
        <title>
            simply-chris | Homepage
        </title>
    {% endblock %}
    {% include 'tim/include/css.html' %}
    {% block my_static %}{% endblock %}
</head>

<body class="landing-page ">
    {% include 'tim/include/third_parties.html' %}
    {% include 'tim/include/navbar.html' %}
    {% block content %}
    <div class="page-header header-filter" data-parallax="true" style=" background-image: url('{% static 'assets/img/slider.jpg' %}'); ">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <h1 class="title">Your Story Starts With Us.</h1>
                    <h4>In a sea of ordinary, make sure your website is set apart from the competition.</h4>
                    <br>
                    <a href="{% url 'about_eng' %}" class="btn btn-danger btn-raised btn-lg">
                        <i class="fa fa-play"> </i> Contact Me!
                    </a>
                </div>
            </div>
        </div>
    </div>
    <div class="main main-raised">
        <div class="container">
            <div class="section text-center">
                <div class="row">
                    <div class="col-md-8 ml-auto mr-auto">
                        <h2 class="title">Projects</h2>
                        <h5 class="description">See the latest works</h5>
                    </div>
                </div>
                <div class="features">
                    <div class="row">
                        {% for project in projects %}
                            <div class="col-md-4">
                                <div class="team-player">
                                    <div class="card card-plain">
                                        <div class="col-md-6 ml-auto mr-auto">
                                            <img src="{{ project.image.url }}" alt="Thumbnail Image" class="img-raised rounded-circle img-fluid">
                                        </div>
                                        <h4 class="card-title">{{ project.title_eng }}
                                            <br>
                                            <small class="card-description text-muted">{{ project.category.title_eng }}</small>
                                        </h4>
                                        <div class="card-body">
                                            <p class="card-description">{{ project.short_description_eng }}</p>
                                        </div>
                                        <div class="card-footer justify-content-center">
                                            <a href="{% url 'project_page_eng' project.slug %}" class="btn btn-raised">Details</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
            <div class="section text-center">
                <h2 class="title">Blog</h2>
                <div class="team">
                    <div class="row">
                        <script async src="//cdn.embedly.com/widgets/platform.js" charset="UTF-8"></script>
                        <div class="col-md-6">
                            <blockquote class="embedly-card" data-card-controls="0">
                                <h4><a href="https://medium.com/@christosstath10/django-expenses-7dfd8fb13fc9">Django Expenses - Christos Stathakis - Medium</a></h4>
                                <p>Be aware because is on free tier of heroku maybe will be need on first visit about 20-30 sec to load, then anything is fine!
                                    And if you want to add data We will create a webapp, which we will add our...</p>
                            </blockquote>
                        </div>
                        <div class="col-md-6">
                            <blockquote class="embedly-card" data-card-controls="0">
                                <h4><a href="https://medium.com/@christosstath10/a-story-about-django-react-and-a-cafe-restaurant-webapp-part-1-backend-337bb9b0311e">A Story about Django, React and a cafe restaurant webapp. Part 1 BackEnd</a></h4>
                                <p>In this tutorial we will create a API with Django and Rest Framework, which will manage, save and store all the data React will send us A live api can be found here → https://react-pos.herokuapp.com/api/ On this two part tutorial, our plan is to create two different technologies on each part.</p>
                            </blockquote>
                        </div>
                        <div class="col-md-6">
                            <blockquote class="embedly-card" data-card-controls="0">
                                <h4><a href="https://medium.com/@christosstath10/pos-react-frontend-f04177d9db0">A Story about Django React and restaurant webapp. Part 2 Frontend.</a></h4>
                                <p>A little explain... this guide is for building a Cafe or Restaurant Order Management App.
                                    This is the second part of the series . The Part One is for building the backend with django and rest
                                    framework and you can find it here. In this guide we will use React for building the frontend.</p>
                            </blockquote>
                        </div>
                        {% comment %}
                        {% for post in posts %}
                            <div class="col-md-6">
                            <div class="card card-profile card-plain">
                                <div class="row">
                                    <div class="col-md-5">
                                        <div class="card-header card-header-image">
                                            <a href="{% url 'blog_page_eng' post.slug %}">
                                                <img class="img" src="{{ post.file.url }}">
                                            </a>
                                        </div>
                                    </div>
                                    <div class="col-md-7">
                                        <div class="card-body">
                                            <h4 class="card-title">{{ post.title_eng }}</h4>
                                            <h6 class="category text-muted">{{ post.category_eng }}</h6>
                                            <p class="card-description">
                                                {{ post.content_eng|truncatechars:50|safe }}
                                            </p>
                                        </div>
                                        <div class="card-footer justify-content-center">
                                            <a href="{% url 'blog_page_eng' post.slug %}" class="btn btn-raised">Details</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                        {% endcomment %}
                    </div>
                </div>
            </div>
            <div class="section section-contacts">
                <div class="row">
                    <div class="col-md-8 ml-auto mr-auto">
                        <h2 class="text-center title">About</h2>
                        <div class="row">
                            <div class="col-md-6">
                                <h4 class="text-center description">
                                    My name is Christos Stathakis and i am living in Greece.
                                    I am a web developer using Python , Django, React etc, and
                                    i am learning casual programing about machine learning etc.
                                </h4>
                            </div>
                            <div class="col-md-6">
                                <img src="{% static 'assets/img/personal.jpg' %}" class="img img-responsive img-rounded img-thumbnail">
                            </div>
                        </div>
                        <br><br>
                    </div>
                    <div class="subscribe-line">
                        <div class="container">
                            <div class="row">
                                <div class="col-md-6">
                                    <h3 class="title">Get Tips &amp; Tricks every Week!</h3>
                                    <p class="description">
                                        Join our newsletter and get news in your inbox every week! We hate spam too, so no worries about this.
                                    </p>
                                </div>
                                <div class="col-md-6">
                                    <div class="card card-plain card-form-horizontal">
                                        <div class="card-body">
                                            <form method="post">{% csrf_token %}
                                                <div class="row">
                                                    <div class="col-md-8">
                                                        <div class="input-group">
                                                            <div class="input-group-prepend">
                                                                <span class="input-group-text">
                                                                    <i class="material-icons">mail</i>
                                                                </span>
                                                            </div>
                                                            <input type="email" name="email" class="form-control" placeholder="Fill with your email" required id="id_email" />
                                                            <br>
                                                        </div>
                                                        <div class="input-group">
                                                            <div class="input-group-prepend">
                                                                <span class="input-group-text">
                                                                    Agree to send me emails!
                                                                </span>
                                                            </div>
                                                            <input type="checkbox" name="accept_" class="form-control" placeholder="Fill with your email" required id="id_accept_" />
                                                        </div>
                                                    </div>
                                                    <div class="col-md-4">
                                                        <button type="submit" class="btn btn-primary btn-round btn-block">Subscribe</button>
                                                    </div>
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endblock %}
    <br><br>
    <div class="main main-raised">{% include 'tim/include/europe_cookie.html' %}</div>
    <br>
    <footer class="footer ">
        <div class="container">
            <nav class="pull-left">
                <ul>
                    <li>
                        <a href="{% url 'homepage_eng' %}">
                            Home
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'about_eng' %}">
                            About Us
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'blog_eng' %}">
                            Blog
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'gallery_eng' %}">
                            Projects
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'sample-templates' %}">
                            Samples
                        </a>
                    </li>
                </ul>
            </nav>
            <div class="copyright pull-right">
                &copy;
                <script>
                    document.write(new Date().getFullYear())
                </script>, Template created by
                <a href="https://www.creative-tim.com" target="_blank">Template creative Tim</a>.
                Designed by Christos Stathakis
            </div>
        </div>
    </footer>
    {% include 'tim/include/js.html' %}
    {% block additional_js %}{% endblock %}

</body>

</html>